apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: spring-boot-prometheus
build:
  artifacts:
  - image: docker.io/softvisionlvcp/spring-boot-prometheus
    jib: {}
  tagPolicy:
    sha256: {}

deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml

portForward:
  - resourceType: deployment
    resourceName: demo # must match k8 deployment app name
    port: 8080
    localPort: 8080