apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
        - image: docker.io/softvisionlvcp/spring-boot-prometheus
          name: spring-boot-prometheus
          ports:
            - containerPort: 8080
          resources: {}
status: {}